version: "3" 
services:
  # Web service layer
  # nginx:
  #   image: nginx:1.13
  #   volumes:
  #     - "./:/var/www/html"
  #     - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
  #   ports:
  #     - "81:80"
  #   depends_on:
  #     - php

  # Application service layer
  php:
    build:
      context: ./config/php
    volumes:
      - ".:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=Admin@123
    stdin_open: true
    tty: true
  
  # Data persistence service layer
  mysql:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: dbMySQL
    volumes:
      - "./db_data:/var/lib/mysql"
      - "./config/mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  # PhpMyAdmin for MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  db_data:
